fix(ci): skip verify pull request workflow when no significant files changed

diff --git a/.github/workflows/verify-pull-request.yml b/.github/workflows/verify-pull-request.yml
--- a/.github/workflows/verify-pull-request.yml
+++ b/.github/workflows/verify-pull-request.yml
@@ -9,7 +9,12 @@ on:
       - dev
 
 jobs:
-  verify-pull-request:
+  check-changed-files-count:
+    outputs:
+      count: ${{ steps.changed-files.outputs.all_changed_files_count }}
+      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
+    permissions:
+      actions: 'write'
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -32,27 +37,30 @@ jobs:
         id: changed-files
         uses: tj-actions/changed-files@v41
         with:
+          negation_patterns_first: true
           files_ignore: |
-            yarn.lock
-            **/*.{svg,png,jpg,jpeg,ttf}
+            **
+            !src
+            src/**/*.{jpg,jpeg,png,pneg,svg,webp,mp4,webm,ogg,mp3,wav,flac,aac,wma,flv,avi,mov,wmv,mpg,mkv,flv,3gp,3g2,ts,mts,m2ts,vob,asf,rm,rmvb,dat,iso,zip,rar,7z,tar,gz,tgz,arj,ace,deb,apk,exe,msi,dmg,bin,iso,torrent}
 
       - name: Check changed files
         run: |
-          if [ ${{ github.actor }} == "tomgermanyyyy" ]; then
-            echo "Bypass check changed files for tomgermanyyyy 🚀"
-            exit 0
-          fi
-
           if [ ${{ steps.changed-files.outputs.all_changed_files_count }} -gt 15 ]; then
             echo "Too many files changed. One PR should only change <= 15 files."
             exit 1
           fi
-        continue-on-error: true
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+  lint-and-test:
+    runs-on: ubuntu-latest
+    needs: check-changed-files-count
+    if: needs.check-changed-files-count.outputs.count != '0'
+    steps:
       - name: Add quotes
         id: add-quotes
         run: |
-          echo changed_files_with_quotes="'${{ steps.changed-files.outputs.all_changed_files }}'" | sed "s/ /' '/g" >> "$GITHUB_OUTPUT"
+          echo changed_files_with_quotes="'${{ needs.check-changed-files-count.outputs.changed_files }}'" | sed "s/ /' '/g" >> "$GITHUB_OUTPUT"
         shell: bash
 
       - name: Lint check
@@ -70,8 +78,8 @@ jobs:
           yarn test:cov-json-summary
           exit_code=$?
           if [ $exit_code -ne 0 ]; then
-           echo "Unit tests failed with exit code $exit_code. Stopping the workflow."
-           exit $exit_code
+            echo "Unit tests failed with exit code $exit_code. Stopping the workflow."
+            exit $exit_code
           fi
 
           COVERAGE=$(cat coverage/coverage-summary.json | jq -r '.total.branches.pct')
